### PR TITLE
Paper with graphic abstract, highlights and cover letter ready to review

### PR DESCRIPTION
**Pull request by andrewryh**

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks! Will take a look this week.

**Comment by andrewryh** [comment]
Thanks!

**Comment by katyhuff** [comment]
Hi @andrewryh . Rather than make comments on this PR and go back and forth on it here, I'm going to merge it and then make github issues covering the things that will need to be corrected. That way, the PRs that solve the issues can be more easily reviewed. I'll be adding issues to this over the next few days.

**Comment by andrewryh** [comment]
Okay

**Pull request merged**
